=== Build LinuxKit
[2019-05-07 22:59.41] Starting...
Cloning into '/tmp/with_clone3277659e'...
done.
HEAD is now at 6f3f37b9b rngd exits after being stopped and resumed
[2019-05-07 22:59.42] Running "cp" "-p" "--" "/gcloud/ci-setup.sh" "/tmp/with_clone3277659e/ci-setup.sh"
[2019-05-07 22:59.42] Building with timeout of 120 minutes
[2019-05-07 22:59.42] Running "/gcloud/create.py" "linuxkit-ci-1"
INFO:oauth2client.transport:Attempting refresh to obtain initial access_token
INFO:oauth2client.client:Refreshing access_token
Traceback (most recent call last):
  File "/gcloud/create.py", line 12, in <module>
    project=common.project, family='linuxkit-ci-builder').execute()
  File "/usr/lib/python2.7/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/googleapiclient/http.py", line 837, in execute
    method=str(self.method), body=self.body, headers=self.headers)
  File "/usr/lib/python2.7/site-packages/googleapiclient/http.py", line 181, in _retry_request
    raise exception
socket.timeout: timed out
[2019-05-07 23:00.43] Removing test VM...
[2019-05-07 23:00.43] Running "/gcloud/destroy.py" "linuxkit-ci-1"
INFO:root:Destroying VM
INFO:oauth2client.transport:Attempting refresh to obtain initial access_token
INFO:oauth2client.client:Refreshing access_token
Traceback (most recent call last):
  File "/gcloud/destroy.py", line 12, in <module>
    resp = common.compute.instances().delete(instance=name, project=common.project, zone=common.zone).execute()
  File "/usr/lib/python2.7/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/googleapiclient/http.py", line 842, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 404 when requesting https://www.googleapis.com/compute/v1/projects/moby-datakit-ci/zones/europe-west1-b/instances/linuxkit-ci-1?alt=json returned "The resource 'projects/moby-datakit-ci/zones/europe-west1-b/instances/linuxkit-ci-1' was not found">
[2019-05-07 23:00.44] Results directory "/tmp/linuxkit-25369a57/_results" not found, so not saving
[2019-05-07 23:00.44] Failed: Command "/gcloud/create.py" "linuxkit-ci-1" exited with status 1
