=== Test LinuxKit on GCP
[2019-05-21 08:53.23] Starting...
INFO:root:Connecting to storage
INFO:root:Getting bucket
INFO:root:Uploading /build-cache/e54f16d97e9ccc42147f0697f4a75b5b274cf92551fb7c7e1f77a7ce41e0b7a2 -> linuxkit-ci-2.tar.gz
INFO:root:Removing old image
INFO:oauth2client.transport:Attempting refresh to obtain initial access_token
INFO:oauth2client.client:Refreshing access_token
INFO:root:Removal failed; assuming image didn't exist: timed out
INFO:root:Creating image: {'name': 'linuxkit-ci-2-test-image', 'rawDisk': {'source': u'https://www.googleapis.com/storage/v1/b/linuxkit-gcp-test-bucket/o/linuxkit-ci-2.tar.gz'}}
INFO:oauth2client.transport:Attempting refresh to obtain initial access_token
INFO:oauth2client.client:Refreshing access_token
Traceback (most recent call last):
  File "/gcloud/test.py", line 50, in <module>
    image_response = common.compute.images().insert(project=common.project, body=body).execute()
  File "/usr/lib/python2.7/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/googleapiclient/http.py", line 842, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 409 when requesting https://www.googleapis.com/compute/v1/projects/moby-datakit-ci/global/images?alt=json returned "The resource 'projects/moby-datakit-ci/global/images/linuxkit-ci-2-test-image' already exists">
[2019-05-21 08:54.25] Removing test VM...
[2019-05-21 08:54.25] Running "/gcloud/destroy.py" "linuxkit-ci-2"
INFO:root:Destroying VM
INFO:oauth2client.transport:Attempting refresh to obtain initial access_token
INFO:oauth2client.client:Refreshing access_token
Traceback (most recent call last):
  File "/gcloud/destroy.py", line 12, in <module>
    resp = common.compute.instances().delete(instance=name, project=common.project, zone=common.zone).execute()
  File "/usr/lib/python2.7/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/googleapiclient/http.py", line 842, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 404 when requesting https://www.googleapis.com/compute/v1/projects/moby-datakit-ci/zones/europe-west1-b/instances/linuxkit-ci-2?alt=json returned "The resource 'projects/moby-datakit-ci/zones/europe-west1-b/instances/linuxkit-ci-2' was not found">
[2019-05-21 08:54.26] Failed: Command "/gcloud/test.py" "/build-cache/e54f16d97e9ccc42147f0697f4a75b5b274cf92551fb7c7e1f77a7ce41e0b7a2" "linuxkit-ci-2" exited with status 1
